package modelo;
// Generated 17/03/2023 20:30:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblactividades generated by hbm2java
 */
public class Tblactividades  implements java.io.Serializable {


     private Integer idtblactividad;
     private Tblavances tblavances;
     private Tblpagos tblpagos;
     private Tblproyectos tblproyectos;
     private Tblusuarios tblusuarios;
     private String actividad;
     private BigDecimal valorRefer;
     private Integer idcanton;
     private String codigopoa;
     private String descripcion;
     private Integer idestado;
     private String antecedente;
     private Integer peso;
     private Date fechaInicio;
     private Integer duracion;
     private Date inicioReal;
     private Date finReal;
     private Set tblpresupuestoses = new HashSet(0);

    public Tblactividades() {
    }

    public Tblactividades(Tblavances tblavances, Tblpagos tblpagos, Tblproyectos tblproyectos, Tblusuarios tblusuarios, String actividad, BigDecimal valorRefer, Integer idcanton, String codigopoa, String descripcion, Integer idestado, String antecedente, Integer peso, Date fechaInicio, Integer duracion, Date inicioReal, Date finReal, Set tblpresupuestoses) {
       this.tblavances = tblavances;
       this.tblpagos = tblpagos;
       this.tblproyectos = tblproyectos;
       this.tblusuarios = tblusuarios;
       this.actividad = actividad;
       this.valorRefer = valorRefer;
       this.idcanton = idcanton;
       this.codigopoa = codigopoa;
       this.descripcion = descripcion;
       this.idestado = idestado;
       this.antecedente = antecedente;
       this.peso = peso;
       this.fechaInicio = fechaInicio;
       this.duracion = duracion;
       this.inicioReal = inicioReal;
       this.finReal = finReal;
       this.tblpresupuestoses = tblpresupuestoses;
    }
   
    public Integer getIdtblactividad() {
        return this.idtblactividad;
    }
    
    public void setIdtblactividad(Integer idtblactividad) {
        this.idtblactividad = idtblactividad;
    }
    public Tblavances getTblavances() {
        return this.tblavances;
    }
    
    public void setTblavances(Tblavances tblavances) {
        this.tblavances = tblavances;
    }
    public Tblpagos getTblpagos() {
        return this.tblpagos;
    }
    
    public void setTblpagos(Tblpagos tblpagos) {
        this.tblpagos = tblpagos;
    }
    public Tblproyectos getTblproyectos() {
        return this.tblproyectos;
    }
    
    public void setTblproyectos(Tblproyectos tblproyectos) {
        this.tblproyectos = tblproyectos;
    }
    public Tblusuarios getTblusuarios() {
        return this.tblusuarios;
    }
    
    public void setTblusuarios(Tblusuarios tblusuarios) {
        this.tblusuarios = tblusuarios;
    }
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }
    public BigDecimal getValorRefer() {
        return this.valorRefer;
    }
    
    public void setValorRefer(BigDecimal valorRefer) {
        this.valorRefer = valorRefer;
    }
    public Integer getIdcanton() {
        return this.idcanton;
    }
    
    public void setIdcanton(Integer idcanton) {
        this.idcanton = idcanton;
    }
    public String getCodigopoa() {
        return this.codigopoa;
    }
    
    public void setCodigopoa(String codigopoa) {
        this.codigopoa = codigopoa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }
    public String getAntecedente() {
        return this.antecedente;
    }
    
    public void setAntecedente(String antecedente) {
        this.antecedente = antecedente;
    }
    public Integer getPeso() {
        return this.peso;
    }
    
    public void setPeso(Integer peso) {
        this.peso = peso;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public Date getInicioReal() {
        return this.inicioReal;
    }
    
    public void setInicioReal(Date inicioReal) {
        this.inicioReal = inicioReal;
    }
    public Date getFinReal() {
        return this.finReal;
    }
    
    public void setFinReal(Date finReal) {
        this.finReal = finReal;
    }
    public Set getTblpresupuestoses() {
        return this.tblpresupuestoses;
    }
    
    public void setTblpresupuestoses(Set tblpresupuestoses) {
        this.tblpresupuestoses = tblpresupuestoses;
    }
    public String getEstado_texto()
    {String miestado="Activo";
        switch(this.idestado)
        {
            case 1:miestado="Activo";break;
            case 2:miestado="Iniciado";break;
            case 3:miestado="Finalizado";break;
            case 4:miestado="Anulada";break;
        }
        return miestado;
    }



}


