package modelo;
// Generated 17/03/2023 20:30:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblcargos generated by hbm2java
 */
public class Tblcargos  implements java.io.Serializable {


     private Integer idtblcargo;
     private String cargo;
     private Set tblusuarioses = new HashSet(0);

    public Tblcargos() {
    }

    public Tblcargos(String cargo, Set tblusuarioses) {
       this.cargo = cargo;
       this.tblusuarioses = tblusuarioses;
    }
   
    public Integer getIdtblcargo() {
        return this.idtblcargo;
    }
    
    public void setIdtblcargo(Integer idtblcargo) {
        this.idtblcargo = idtblcargo;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Set getTblusuarioses() {
        return this.tblusuarioses;
    }
    
    public void setTblusuarioses(Set tblusuarioses) {
        this.tblusuarioses = tblusuarioses;
    }




}


