package modelo;
// Generated 17/03/2023 20:30:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblinsumos generated by hbm2java
 */
public class Tblinsumos  implements java.io.Serializable {


     private int idtblinsumo;
     private String mision;
     private String vision;
     private String valores;
     private String pot;
     private Date anio;

    public Tblinsumos() {
    }

	
    public Tblinsumos(int idtblinsumo) {
        this.idtblinsumo = idtblinsumo;
    }
    public Tblinsumos(int idtblinsumo, String mision, String vision, String valores, String pot, Date anio) {
       this.idtblinsumo = idtblinsumo;
       this.mision = mision;
       this.vision = vision;
       this.valores = valores;
       this.pot = pot;
       this.anio = anio;
    }
   
    public int getIdtblinsumo() {
        return this.idtblinsumo;
    }
    
    public void setIdtblinsumo(int idtblinsumo) {
        this.idtblinsumo = idtblinsumo;
    }
    public String getMision() {
        return this.mision;
    }
    
    public void setMision(String mision) {
        this.mision = mision;
    }
    public String getVision() {
        return this.vision;
    }
    
    public void setVision(String vision) {
        this.vision = vision;
    }
    public String getValores() {
        return this.valores;
    }
    
    public void setValores(String valores) {
        this.valores = valores;
    }
    public String getPot() {
        return this.pot;
    }
    
    public void setPot(String pot) {
        this.pot = pot;
    }
    public Date getAnio() {
        return this.anio;
    }
    
    public void setAnio(Date anio) {
        this.anio = anio;
    }




}


