package modelo;
// Generated 17/03/2023 20:30:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tbllog generated by hbm2java
 */
public class Tbllog  implements java.io.Serializable {


     private Integer idlog;
     private Date fechahora;
     private String observacion;
     private String usuario;
     private Integer idactividad;

    public Tbllog() {
    }

	
    public Tbllog(Date fechahora) {
        this.fechahora = fechahora;
    }
    public Tbllog(Date fechahora, String observacion, String usuario, Integer idactividad) {
       this.fechahora = fechahora;
       this.observacion = observacion;
       this.usuario = usuario;
       this.idactividad = idactividad;
    }
   
    public Integer getIdlog() {
        return this.idlog;
    }
    
    public void setIdlog(Integer idlog) {
        this.idlog = idlog;
    }
    public Date getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(Date fechahora) {
        this.fechahora = fechahora;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Integer getIdactividad() {
        return this.idactividad;
    }
    
    public void setIdactividad(Integer idactividad) {
        this.idactividad = idactividad;
    }




}


