package modelo;
// Generated 17/03/2023 20:30:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblobjetivos generated by hbm2java
 */
public class Tblobjetivos  implements java.io.Serializable {


     private Integer idtblobjetivo;
     private String objetivo;
     private String nivel;
     private Integer iddireccion;
     private Integer idperiodo;
     private Set tblprogramases = new HashSet(0);

    public Tblobjetivos() {
    }

    public Tblobjetivos(String objetivo, String nivel, Integer iddireccion, Integer idperiodo, Set tblprogramases) {
       this.objetivo = objetivo;
       this.nivel = nivel;
       this.iddireccion = iddireccion;
       this.idperiodo = idperiodo;
       this.tblprogramases = tblprogramases;
    }
   
    public Integer getIdtblobjetivo() {
        return this.idtblobjetivo;
    }
    
    public void setIdtblobjetivo(Integer idtblobjetivo) {
        this.idtblobjetivo = idtblobjetivo;
    }
    public String getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public Integer getIddireccion() {
        return this.iddireccion;
    }
    
    public void setIddireccion(Integer iddireccion) {
        this.iddireccion = iddireccion;
    }
    public Integer getIdperiodo() {
        return this.idperiodo;
    }
    
    public void setIdperiodo(Integer idperiodo) {
        this.idperiodo = idperiodo;
    }
    public Set getTblprogramases() {
        return this.tblprogramases;
    }
    
    public void setTblprogramases(Set tblprogramases) {
        this.tblprogramases = tblprogramases;
    }




}


