package modelo;
// Generated 17/03/2023 20:30:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblpagos generated by hbm2java
 */
public class Tblpagos  implements java.io.Serializable {


     private int idtblpagos;
     private BigDecimal pago;
     private Integer mes;
     private Date anio;
     private Integer idactividad;
     private Set tblactividadeses = new HashSet(0);

    public Tblpagos() {
    }

	
    public Tblpagos(int idtblpagos) {
        this.idtblpagos = idtblpagos;
    }
    public Tblpagos(int idtblpagos, BigDecimal pago, Integer mes, Date anio, Integer idactividad, Set tblactividadeses) {
       this.idtblpagos = idtblpagos;
       this.pago = pago;
       this.mes = mes;
       this.anio = anio;
       this.idactividad = idactividad;
       this.tblactividadeses = tblactividadeses;
    }
   
    public int getIdtblpagos() {
        return this.idtblpagos;
    }
    
    public void setIdtblpagos(int idtblpagos) {
        this.idtblpagos = idtblpagos;
    }
    public BigDecimal getPago() {
        return this.pago;
    }
    
    public void setPago(BigDecimal pago) {
        this.pago = pago;
    }
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }
    public Date getAnio() {
        return this.anio;
    }
    
    public void setAnio(Date anio) {
        this.anio = anio;
    }
    public Integer getIdactividad() {
        return this.idactividad;
    }
    
    public void setIdactividad(Integer idactividad) {
        this.idactividad = idactividad;
    }
    public Set getTblactividadeses() {
        return this.tblactividadeses;
    }
    
    public void setTblactividadeses(Set tblactividadeses) {
        this.tblactividadeses = tblactividadeses;
    }




}


