package modelo;
// Generated 17/03/2023 20:30:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblparpre generated by hbm2java
 */
public class Tblparpre  implements java.io.Serializable {


     private int idtblparpre;
     private String partida;
     private Integer activo;
     private Set tblpresupuestoses = new HashSet(0);

    public Tblparpre() {
    }

	
    public Tblparpre(int idtblparpre) {
        this.idtblparpre = idtblparpre;
    }
    public Tblparpre(int idtblparpre, String partida, Integer activo, Set tblpresupuestoses) {
       this.idtblparpre = idtblparpre;
       this.partida = partida;
       this.activo = activo;
       this.tblpresupuestoses = tblpresupuestoses;
    }
   
    public int getIdtblparpre() {
        return this.idtblparpre;
    }
    
    public void setIdtblparpre(int idtblparpre) {
        this.idtblparpre = idtblparpre;
    }
    public String getPartida() {
        return this.partida;
    }
    
    public void setPartida(String partida) {
        this.partida = partida;
    }
    public Integer getActivo() {
        return this.activo;
    }
    
    public void setActivo(Integer activo) {
        this.activo = activo;
    }
    public Set getTblpresupuestoses() {
        return this.tblpresupuestoses;
    }
    
    public void setTblpresupuestoses(Set tblpresupuestoses) {
        this.tblpresupuestoses = tblpresupuestoses;
    }




}


