package modelo;
// Generated 17/03/2023 20:30:04 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tblpresupuestos generated by hbm2java
 */
public class Tblpresupuestos  implements java.io.Serializable {


     private Integer idtblpresupuesto;
     private Tblactividades tblactividades;
     private Tblparpre tblparpre;
     private BigDecimal monto;

    public Tblpresupuestos() {
    }

    public Tblpresupuestos(Tblactividades tblactividades, Tblparpre tblparpre, BigDecimal monto) {
       this.tblactividades = tblactividades;
       this.tblparpre = tblparpre;
       this.monto = monto;
    }
   
    public Integer getIdtblpresupuesto() {
        return this.idtblpresupuesto;
    }
    
    public void setIdtblpresupuesto(Integer idtblpresupuesto) {
        this.idtblpresupuesto = idtblpresupuesto;
    }
    public Tblactividades getTblactividades() {
        return this.tblactividades;
    }
    
    public void setTblactividades(Tblactividades tblactividades) {
        this.tblactividades = tblactividades;
    }
    public Tblparpre getTblparpre() {
        return this.tblparpre;
    }
    
    public void setTblparpre(Tblparpre tblparpre) {
        this.tblparpre = tblparpre;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


