package modelo;
// Generated 17/03/2023 20:30:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblprogramas generated by hbm2java
 */
public class Tblprogramas  implements java.io.Serializable {


     private Integer idtblprogramas;
     private Tblobjetivos tblobjetivos;
     private String programa;
     private String tipo;
     private Integer peso;
     private String codigopoa;
     private Set tblproyectoses = new HashSet(0);

    public Tblprogramas() {
    }

    public Tblprogramas(Tblobjetivos tblobjetivos, String programa, String tipo, Integer peso, String codigopoa, Set tblproyectoses) {
       this.tblobjetivos = tblobjetivos;
       this.programa = programa;
       this.tipo = tipo;
       this.peso = peso;
       this.codigopoa = codigopoa;
       this.tblproyectoses = tblproyectoses;
    }
   
    public Integer getIdtblprogramas() {
        return this.idtblprogramas;
    }
    
    public void setIdtblprogramas(Integer idtblprogramas) {
        this.idtblprogramas = idtblprogramas;
    }
    public Tblobjetivos getTblobjetivos() {
        return this.tblobjetivos;
    }
    
    public void setTblobjetivos(Tblobjetivos tblobjetivos) {
        this.tblobjetivos = tblobjetivos;
    }
    public String getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(String programa) {
        this.programa = programa;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Integer getPeso() {
        return this.peso;
    }
    
    public void setPeso(Integer peso) {
        this.peso = peso;
    }
    public String getCodigopoa() {
        return this.codigopoa;
    }
    
    public void setCodigopoa(String codigopoa) {
        this.codigopoa = codigopoa;
    }
    public Set getTblproyectoses() {
        return this.tblproyectoses;
    }
    
    public void setTblproyectoses(Set tblproyectoses) {
        this.tblproyectoses = tblproyectoses;
    }




}


