package modelo;
// Generated 17/03/2023 20:30:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblusuarios generated by hbm2java
 */
public class Tblusuarios  implements java.io.Serializable {


     private Integer idtblusuario;
     private Tblcargos tblcargos;
     private Tbldirecciones tbldirecciones;
     private String nombre;
     private String usuario;
     private String clave;
     private Byte activo;
     private Set tblactividadeses = new HashSet(0);
     private Set tblaccesousus = new HashSet(0);

    public Tblusuarios() {
    }

    public Tblusuarios(Tblcargos tblcargos, Tbldirecciones tbldirecciones, String nombre, String usuario, String clave, Byte activo, Set tblactividadeses, Set tblaccesousus) {
       this.tblcargos = tblcargos;
       this.tbldirecciones = tbldirecciones;
       this.nombre = nombre;
       this.usuario = usuario;
       this.clave = clave;
       this.activo = activo;
       this.tblactividadeses = tblactividadeses;
       this.tblaccesousus = tblaccesousus;
    }
   
    public Integer getIdtblusuario() {
        return this.idtblusuario;
    }
    
    public void setIdtblusuario(Integer idtblusuario) {
        this.idtblusuario = idtblusuario;
    }
    public Tblcargos getTblcargos() {
        return this.tblcargos;
    }
    
    public void setTblcargos(Tblcargos tblcargos) {
        this.tblcargos = tblcargos;
    }
    public Tbldirecciones getTbldirecciones() {
        return this.tbldirecciones;
    }
    
    public void setTbldirecciones(Tbldirecciones tbldirecciones) {
        this.tbldirecciones = tbldirecciones;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Byte getActivo() {
        return this.activo;
    }
    
    public void setActivo(Byte activo) {
        this.activo = activo;
    }
    public Set getTblactividadeses() {
        return this.tblactividadeses;
    }
    
    public void setTblactividadeses(Set tblactividadeses) {
        this.tblactividadeses = tblactividadeses;
    }
    public Set getTblaccesousus() {
        return this.tblaccesousus;
    }
    
    public void setTblaccesousus(Set tblaccesousus) {
        this.tblaccesousus = tblaccesousus;
    }




}


